version: "3.9"
services:
  bot:
    container_name: phackbot
    build: discordbot/.
    environment:
      DC_ENV: production

  backend:
    container_name: phackbotApi
    build: backend/.
    ports:
      - "1377:1377"
